// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBlog.Context;

namespace MyBlog.Migrations
{
    [DbContext(typeof(MyBlogContext))]
    partial class MyBlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyBlog.Models.Blog.Entity.BlogArticle", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("BlogId")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ClassId")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EditTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PraiseCount")
                        .HasColumnType("int");

                    b.Property<int>("ReadCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(128)");

                    b.HasKey("ArticleId");

                    b.ToTable("BlogArticle");
                });

            modelBuilder.Entity("MyBlog.Models.Blog.Entity.BlogClass", b =>
                {
                    b.Property<string>("ClassId")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("BlogId")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ClassName")
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("OrderID")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("ParentId")
                        .HasColumnType("varchar(32)");

                    b.HasKey("ClassId");

                    b.ToTable("BlogClass");
                });

            modelBuilder.Entity("MyBlog.Models.Blog.Entity.BlogInfo", b =>
                {
                    b.Property<string>("BlogId")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("BlogName")
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(32)");

                    b.HasKey("BlogId");

                    b.ToTable("BlogInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
